### ISSUE TITLE
Could we have a possibility to find works referenced by a specified work?

### ISSUE THREAD

**Issue by 0xorial** [ourresearch/openalex-api#2]
Hi! Very happy to see that the API is already available online!

First, a small question: could you confirm that this repo is the source code of the version deployed at https://api.openalex.org/ ? I see that there haven't been new commits here since October, which seems strange.

Second, currently the work entity contains a list of referenced, but only as a list of urls, so to get further information we need to make as many calls as there are references in a certain work. 
Do you think it is feasible to add another search filter, that would allow getting all works referenced by the specified work? Being a programmer myself I would be happy to try and make a PR if you can give me some rough pointers.

**Comment by jasonpriem** [comment]
1) OpenAlex is a pretty big project, and so the code is actually split into a bunch of different applications, each of which have their own repository. You can find them all by searching our org for "openalex-" like this: https://github.com/search?q=org%3Aourresearch+openalex-

2) Sorry, we don't currently have plans for a filter like this. We did recently speed up the entity API so when you make those individual API calls they will come back in <500ms each, and since the API limit is very high you don't need to worry about how many calls you're making.
